// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://akxahbedrtxmmrajwejy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFreGFoYmVkcnR4bW1yYWp3ZWp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNDIwMjcsImV4cCI6MjA2MjYxODAyN30.4QgzHRKPyDbj0IsrhZlQZOlF-4I4Mig5tMSYF-2V9L8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);